app.py
from flask import Flask
from routes import main

app = Flask(__name__)
app.register_blueprint(main)

if __name__ == "__main__":
    app.run(debug=True)

routes.py
from flask import Blueprint, render_template, redirect
from apimercadopago import criar_link_pagamento
from conexao import conectar

main = Blueprint("main", __name__)


@main.route("/")
def homepage():
    conn = conectar()
    cur = conn.cursor()

    cur.execute("SELECT id, nome_produto, preco, estoque FROM apimercadopago")
    produtos = cur.fetchall()

    
    return render_template("homepage.html", produtos=produtos)

@main.route("/comprar/<produto_id>")
def comprar(produto_id):
    conn = conectar()
    cur = conn.cursor()

    cur.execute('''
        SELECT id, nome_produto, preco, estoque 
        FROM apimercadopago
        WHERE id = %s
                          ''', (produto_id,))
    produto = cur.fetchone()

    
  
    if not produto:
        return "Produto não encontrado", 404
    

    product_list = {
        "id":produto[0],
        "title":produto[1],
        "quantity":1,
        "unit_price":float(produto[2]),

    }

    link = criar_link_pagamento(product_list)
    if link:
        return redirect(link)
        
    else:
        return "Erro ao criar link de pagamento", 500

templates/homepage.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Marketplace do Jorge</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <h1>Produtos disponíveis</h1>

    <div class="container">
        {% for p in produtos %}
            <div class="produto">
                <h2>{{ p[1] }}</h2> <!-- nome_produto -->
                <p>Preço: R$ {{ "%.2f"|format(p[2]) }}</p> <!-- preco -->
                <p>Estoque: {{ p[3] }}</p> <!-- estoque -->
                <a href="{{ url_for('main.comprar', produto_id=p[0]) }}" class="btn">Comprar</a> <!-- id -->
            </div>
        {% endfor %}
    </div>
</body>
</html>